name: Test JSON Parsing

on:
  workflow_dispatch:
    inputs:
      publishedPackages:
        description: "JSON string of published packages"
        required: true
        default: '[{"name": "@shopify/hydrogen", "version": "1.2.3"}, {"name": "@shopify/other", "version": "2.0.0"}]'

jobs:
  test_json_parsing:
    runs-on: ubuntu-latest
    steps:
      - name: Test fromJson function
        run: |
          echo "Published Packages: ${{ inputs.publishedPackages }}"

      - name: Extract Hydrogen version
        id: extract_version
        run: |
          PACKAGES='${{ inputs.publishedPackages }}'
          HYDROGEN_VERSION=$(echo $PACKAGES | jq -r '.[] | select(.name == "@shopify/hydrogen") | .version')
          echo "HYDROGEN_VERSION=$HYDROGEN_VERSION"
          echo "HYDROGEN_VERSION=$HYDROGEN_VERSION" >> $GITHUB_ENV
      - name: Print Hydrogen version
        run: |
          echo "Extracted Hydrogen version: ${{ env.HYDROGEN_VERSION }}"
